{application,dia,
             [{description,"Diameter relay agent instance"},
              {vsn,"0.0.1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{dia_app,[]}},
              {env,[]},
              {modules,[client,client_cb,dia_app,dia_sup,i_relay_cb,irelay,
                        node,o_relay_cb,orelay,relay_manager,server,
                        server_cb]}]}.
